package ui

// HelpSection is one group of keybindings shown in the ? help overlay
// and in the Keybindings section of README.md (generated by `make docs`).
type HelpSection struct {
	Title string
	Rows  [][2]string // {key, description}
}

// HelpSections is the single source of truth for all keybindings.
// Edit here → `make docs` regenerates the README.md keybindings section.
var HelpSections = []HelpSection{
	{"Navigation", [][2]string{
		{"j / k", "move down / up"},
		{"gg", "jump to top"},
		{"G", "jump to bottom"},
		{"enter / l", "open email"},
		{"h / q / esc", "back to inbox (from reader)"},
		{"?", "toggle help overlay (type to filter)"},
	}},
	{"Folders", [][2]string{
		{"L / tab", "next folder tab"},
		{"H / shift+tab", "previous folder tab"},
		{"gi", "go to Inbox"},
		{"ga", "go to Archive"},
		{"gf", "go to Feed"},
		{"gp", "go to PaperTrail"},
		{"gt", "go to Trash"},
		{"gs", "go to Sent"},
		{"gk", "go to ToScreen"},
		{"go", "go to ScreenedOut"},
		{"gw", "go to Waiting"},
		{"gm", "go to Someday"},
		{"gd", "go to Drafts (read-only; save-to-draft not yet implemented)"},
		{"gS", "go to Spam (not in tab rotation)"},
	}},
	{"Screener  (marked or cursor, any folder)", [][2]string{
		{"I", "approve sender → screened_in.txt + move to Inbox (removes from blocked lists)"},
		{"O", "block sender → screened_out.txt + move to ScreenedOut (removes from screened_in)"},
		{"$", "mark as Spam → spam.txt + move to Spam (removes from screened_in/out)"},
		{"F", "mark as Feed → feed.txt + move to Feed"},
		{"P", "mark as PaperTrail → papertrail.txt + move to PaperTrail"},
		{"A", "archive (move to Archive, no screener update)"},
		{"S", "dry-run screen inbox (loaded emails), then y/n"},
	}},
	{"Move  (marked or cursor, no screener update)", [][2]string{
		{"x", "delete → Trash"},
		{"Mi", "move to Inbox"},
		{"Ma", "move to Archive"},
		{"Mf", "move to Feed"},
		{"Mp", "move to PaperTrail"},
		{"Mt", "move to Trash"},
		{"Mo", "move to ScreenedOut"},
		{"Mw", "move to Waiting"},
		{"Mm", "move to Someday"},
	}},
	{"Multi-select", [][2]string{
		{"m", "mark / unmark email + advance cursor"},
		{"U", "clear all marks"},
	}},
	{"Leader Key Mappings (space prefix)", [][2]string{
		{"<space>1 … <space>9", "jump to folder tab by number (Inbox=1, ToScreen=2, …)"},
	}},
	{"Sort  (, prefix)", [][2]string{
		{",m", "date newest first (default)"},
		{",M", "date oldest first"},
		{",a", "from A→Z"},
		{",A", "from Z→A"},
		{",s", "size smallest first"},
		{",S", "size largest first"},
		{",n", "subject A→Z"},
		{",N", "subject Z→A"},
	}},
	{"Email actions", [][2]string{
		{"n", "toggle read/unread  (marked or cursor)"},
		{"ctrl+n", "mark all in current folder as read"},
		{"R", "reload / refresh folder"},
		{"r", "reply  (from reader)"},
		{"c", "compose new email"},
		{"e  (reader)", "open in $EDITOR read-only — search, copy, vim motions"},
		{"o  (reader)", "open in w3m (terminal browser)"},
		{"O  (reader)", "open in $BROWSER (GUI browser, images shown)"},
		{"ctrl+o  (reader)", "open web version / newsletter URL in $BROWSER"},
		{"ctrl+a", "switch account  (if multiple configured)"},
	}},
	{"Command line  (: to open, tab to complete)", [][2]string{
		{":screen  / :s", "dry-run screen loaded inbox emails"},
		{":screen-all  / :sa", "dry-run screen ALL inbox emails (no limit)"},
		{":reset-toscreen  / :rts", "move all ToScreen emails back to Inbox"},
		{":mark-read  / :mr", "mark all emails in current folder as read"},
		{":reload  / :r", "reload current folder"},
		{":check  / :ch", "show screener classification for selected email"},
		{":delete-all  / :da", "permanently delete ALL emails in current folder (y/n)"},
		{":create-folders  / :cf", "create missing IMAP folders from config (safe, idempotent)"},
		{":go-spam  / :spam", "open Spam folder (not in tab rotation)"},
		{":quit  / :q", "quit neomd"},
	}},
	{"Composing", [][2]string{
		{"tab / enter", "move to next field"},
		{"enter  (on Subject)", "open $EDITOR with a .md temp file"},
		{"esc", "cancel"},
	}},
	{"General", [][2]string{
		{"/", "filter emails in current folder"},
		{"?", "toggle this help"},
		{"q", "quit  (from inbox)"},
	}},
}
